# Generated by Django 5.2 on 2025-05-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AminoAcidCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('structure', models.TextField(verbose_name='Строение')),
                ('code', models.CharField(max_length=3, verbose_name='Трёхбуквенный код')),
                ('image', models.ImageField(blank=True, null=True, upload_to='amino_images/', verbose_name='Изображение')),
            ],
        ),
    ]
